name: 'Python composite action'
description: 'A composite action to handle building a python package'

inputs:
  new-tag:
    required: true
    description: 'The new tag to push'
  package-folder:
    required: true
    description: 'Path to setup.py'
    default: './'
    
outputs:
  package:
    description: 'The tag of the new python package'
    value: ${{ steps.echo_name.outputs.package-name }}
    
runs:
    using: "composite"
    steps:
          
      - name: Override version in setup.py
        uses: teveltech/version-action@master
        with:
          new_version: ${{ inputs.new-tag }}
          file_path: ${{ inputs.package-folder }}

      - name: check setup.py
        shell: bash
        run: cat setup.py
        
      - name: Link pypi config directory and .pypirc to github home /github/home
        shell: bash
        run: ln -s /root/.pypirc $HOME/.pypirc && ln -s /root/.pip $HOME/.pip

      - name: Install dependencies needed to upload
        shell: bash
        run: |
          pip3 install setuptools wheel twine
          
      - name: Install dependencies needed to build
        shell: bash
        run: |
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
          if [ -f ${{ inputs.package-folder }}requirements.txt ]; then pip3 install -r ${{ inputs.package-folder }}requirements.txt; fi
          
      - name: Build and publish
        shell: bash
        working-directory: ${{ inputs.package-folder }}
        run: |
          python3 setup.py bdist_wheel upload -r local
          
      - name: get python tag
        id: echo_name
        shell: bash
        working-directory: ${{ inputs.package-folder }}
        run: |
          cat ./*.egg-info/PKG-INFO | \
          awk '/^Name:/ {printf $2"=="} /^Version:/ {print $2}'
          echo "package-name= \
          $(cat ./*.egg-info/PKG-INFO | \
          awk '/^Name:/ {printf $2"=="} /^Version:/ {print $2}')" >> $GITHUB_OUTPUT

      - name: Add to summary
        id: summary
        shell: bash
        run: |
          echo '##### Python package:' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{steps.echo_name.outputs.package-name}}' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

